name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Configuration
      run: |
        CONFIG_ENV=$(grep -w "CONFIG_ENV" config.env | head -n 1 | cut -d "=" -f 2)
        CONFIG_LIST=(
            KERNEL_SOURCE KERNEL_SOURCE_BRANCH KERNEL_CONFIG KERNEL_IMAGE_NAME ARCH 
            ADD_LOCALVERSION_TO_FILENAME EXTRA_CMDS USE_CUSTOM_CLANG CUSTOM_CLANG_SOURCE 
            CUSTOM_CLANG_BRANCH CUSTOM_CMDS CLANG_BRANCH CLANG_VERSION ENABLE_GCC_ARM64 
            ENABLE_GCC_ARM32 USE_CUSTOM_GCC_64 CUSTOM_GCC_64_SOURCE CUSTOM_GCC_64_BRANCH 
            CUSTOM_GCC_64_BIN USE_CUSTOM_GCC_32 CUSTOM_GCC_32_SOURCE CUSTOM_GCC_32_BRANCH 
            CUSTOM_GCC_32_BIN ENABLE_KERNELSU KERNELSU_TAG ADD_KPROBES_CONFIG DISABLE-LTO 
            ADD_OVERLAYFS_CONFIG DISABLE_CC_WERROR APPLY_KSU_PATCH USE_CUSTOM_ANYKERNEL3 
            CUSTOM_ANYKERNEL3_SOURCE CUSTOM_ANYKERNEL3_BRANCH ENABLE_CCACHE NEED_DTBO 
            BUILD_BOOT_IMG SOURCE_BOOT_IMAGE KSU_EXPECTED_SIZE KSU_EXPECTED_HASH REMOVE_UNUSED_PACKAGES
        )
        for CONFIG in "${CONFIG_LIST[@]}"; do
            if [[ "$CONFIG" == "EXTRA_CMDS" || "$CONFIG" == "CUSTOM_CMDS" ]]; then
                echo "$CONFIG=$(grep -w "$CONFIG" "$CONFIG_ENV" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
            else
                echo "$CONFIG=$(grep -w "$CONFIG" "$CONFIG_ENV" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
            fi
        done

    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup build kernel environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace

    - name: Download Custom-Clang
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        rm -rf clang-aosp
        mkdir -p clang-aosp
        echo "Starting stable Clang download..."
        wget --no-check-certificate --tries=5 --retry-connrefused -qO clang.tar.gz https://github.com/ZyCromerZ/Clang/releases/download/14.0.6-20220914-release/ZyCromerZ-Clang-14.0.6-20220914-release.tar.gz
        echo "Extracting Clang..."
        tar -C clang-aosp/ -zxf clang.tar.gz
        if [ -d "clang-aosp/bin" ]; then
            echo "Clang is ready ✅"
            rm clang.tar.gz
        else
            echo "Error: Clang extraction failed ❌"
            exit 1
        fi

    - name: Download Gcc-aosp
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir -p gcc-64 && mkdir -p gcc-32
        wget -qO gcc-64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc-64/ -zxf gcc-64.tar.gz
        wget -qO gcc-32.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc-32/ -zxf gcc-32.tar.gz
        echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin/aarch64-linux-android-" >> $GITHUB_ENV
        echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin/arm-linux-androideabi-" >> $GITHUB_ENV

    - name: Download kernel source
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone --recursive ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1

    - name: Setup KernelSU
      if: env.ENABLE_KERNELSU == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ env.KERNELSU_TAG }}
        echo "UPLOADNAME=-KernelSU" >> $GITHUB_ENV

    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
        make -j$(nproc --all) CC=clang O=out ARCH=arm64 ${{ env.KERNEL_CONFIG }}
        make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }} CLANG_TRIPLE=aarch64-linux-gnu-

    - name: Make Anykernel3
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
        cp android-kernel/out/arch/arm64/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
        rm -rf AnyKernel3/.git*

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-Mi11Ultra
        path: kernel_workspace/AnyKernel3/*
